org: kobst
app: stellium
service: stellium-backend

provider:
  name: aws
  runtime: nodejs20.x 
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource:
            - arn:aws:ssm:us-east-1:*:parameter/stellium/*

functions:
  app:
    handler: server.handler
    timeout: 120
    memorySize: 2048
    architecture: arm64
    environment:
      NODE_OPTIONS: "--expose-gc --max-old-space-size=1536"
      AWS_REGION: us-east-1
    layers:
      - arn:aws:lambda:us-east-1:547054413317:layer:stellium-sweph-layer:4
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: 'https://main.d36g3neun79jnt.amplifyapp.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
            allowCredentials: true
            maxAge: 86400
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: 'https://main.d36g3neun79jnt.amplifyapp.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
            allowCredentials: true
            maxAge: 86400

custom:
  serverless-offline:
    httpPort: 3001

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - '!node_modules/sweph/**'


